### ISSUE TITLE
The color of pictures seems to be  a little red?

### ISSUE THREAD

**Issue by caiduoduo12138** [jgibson2/sea-thru#8]
When I use the project to enhance my underwaterdataset, the color of  outputs is distorted(a little red).  I use the .jpeg format without depth map, how can I set the parameter to solve the problem? Please give me some advice, thanks.

**Comment by jgibson2** [comment]
So, this really depends on your image. The problem is (likely) the white-balancing procedure; if there's no red object in your scene, it will take the reddest thing and make it pure red. So you can solve this with another image editing program, or by playing around with the white balancing functions in the code.
